version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:57"
      timezone: "Europe/London"
      day: "friday"
    commit-message: 
      prefix: "Dependabot (github actions repo workflows and reusable workflows): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
