version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:10"
      timezone: "Europe/London"
      day: "friday"
    commit-message: 
      prefix: "Dependabot (repo and reusable workflows): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/AddTrelloComment"
    schedule:
      interval: "daily"
      time: "16:10"
      timezone: "Europe/London"
    commit-message: 
      prefix: "Dependabot (AddTrelloComment): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/backup-postgres"
    schedule:
      interval: "daily"
      time: "16:10"
      timezone: "Europe/London"
    commit-message: 
      prefix: "Dependabot (backup-postgres): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
